---
- hosts: all
  tasks:
    - name: Enable EPEL Repository on CentOS 7
      yum: 
        name: epel-release
        state: latest
      become: True
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
      become: True
    - name: start nginx
      become: True
      service:
          name: nginx
          state: started